name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build with Make
        run: cmake --build build

      - name: Run Tests with CTest
        run: ctest --test-dir build --verbose
